config/routes.rb
TextVisu::Application.routes.draw do
  post "visualize/render" => "visualize#index" 
  get "visualize/index"

  resources :settings

  root :to => 'visualize#index'

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :name, :value

  def self.for_key(search, default = "")
    set = Setting.find_by_name(search)
    unless set
      set = Setting.create(:name => search, :value => default)
    end
    set.value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/visualize_controller.rb
class VisualizeController < ApplicationController
  before_filter :init_settings

  def index
    session[:navigation_3d] = params[:navigation_3d] if params[:navigation_3d].present?
    session[:show_grid] = params[:show_grid] if params[:show_grid].present?
    session[:text_to_render] = params[:text] if params[:text].present?
    session[:calculation] = params[:calculation] if params[:calculation].present?
    @navigation_3d = session[:navigation_3d]
    @show_grid = session[:show_grid]
    @text_to_render = session[:text_to_render].to_s.downcase || "Dies ist ein Standard Text" 
    @calculation = session[:calculation] || "char"
    @max_cubes_per_line = 0
    @lines = []
    @text_to_render.lines.each do |line|
      @max_cubes_per_line = line.length if line.length > @max_cubes_per_line
      @lines << line.split("").map{|a| {:count => @text_to_render.count(a), :char => a }}
    end
    puts @lines.inspect
  end


  private
  def init_settings
    @cube_size = Setting.for_key("cube_size", 50).to_i
    @cube_padding = Setting.for_key("cube_padding", 10).to_i
    @inner_width = Setting.for_key("inner_width", 800).to_i
    @inner_height = Setting.for_key("inner_height", 500).to_i
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/visualize_helper.rb
module VisualizeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextVisu</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="logo"><%= image_tag "logo.png" %></div>
  <div id="nav">
    <%= link_to "Run Visualization", "/visualize/index", :class => "nav" %>
    <%= link_to "Settings", settings_path(), :class => "nav" %>
  </div>

  <%= yield %>

</body>
</html>

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= @setting.name %>: <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @settings.each do |setting| %>
  <tr>
    <td><%= setting.name %></td>
    <td><%= setting.value %></td>
    <td><%= link_to 'Show', setting %></td>
    <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
    <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @setting.name %>
</p>

<p>
  <b>Value:</b>
  <%= @setting.value %>
</p>


<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>

app/views/visualize/index.html.erb
<script src="/visualize/index.js"></script>

<div id="content">
  <div id="sidebar">  
    <h3>Bitte geben Sie einen Text ein:</h3>
      <%= form_tag "/visualize/render" do  -%>  
        <%= text_area_tag "text", @text_to_render, :id => "text", :placeholder => "Hier den Text eingeben" %>  
        <%= submit_tag "Run Visualization" %>
      <% end -%>  
  </div> 


  <div id="wrapper">
    <div id="container" style="width:<%= @inner_width %>px;"></div>
    <div id="legende" style="width:<%= @inner_width %>px;">
      <ul>
        <% Setting.where("name LIKE '%color_of-%'").order(:name).each do |colorbox| %>
          <li style="background-color:rgb(<%= colorbox.value %>);">
            <div class="label">
              <%= colorbox.name.gsub("color_of-", "").gsub("-(r,g,b)","") %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id="controlls">
    <%= form_tag "/visualize/render", :class => "controll_form" do  -%>  
      <h3>CODIERUNG</h3>
        <div><label class="code <%= @calculation == "char" ? "active" : "" %>"><%= radio_button_tag "calculation", "char", (@calculation == "char") %> Buchstaben</label></div>
        <div><label class="code <%= @calculation == "charcount" ? "active" : "" %>"><%= radio_button_tag "calculation", "charcount", (@calculation == "charcount") %> Buchstabenhäufigkeit</label></div>
        <div><label class="code <%= @calculation == "words" ? "active" : "" %>"><%= radio_button_tag "calculation", "words", (@calculation == "words") %> Worte</label></div>
        <div><label class="code <%= @calculation == "wordcount" ? "active" : "" %>"><%= radio_button_tag "calculation", "wordcount", (@calculation == "wordcount") %> Worthäufigkeit</label></div>
        <%= hidden_field_tag "show_grid", false %>
        <%= hidden_field_tag "navigation_3d", false %>
    
      <h3>Steuerung</h3>
      <a href="#" id="button_up">Vor</a>
      <a href="#" id="button_left">links</a> <a href="#" id="button_right">rechts</a>
      <a href="#" id="button_down">Zurück</a>

      <h3>Ansicht</h3>
      <a href="#" id="button_2d" class="view">2D</a>
      <a href="#" id="button_3d" class="view active">3D</a>
      <div><label class="image <%= @show_grid == "true" ? "active" : "" %>">
        <%= check_box_tag "show_grid", "true", @show_grid == "true" %> Gitter anzeigen
      </label></div>
      <div><label class="image <%= @navigation_3d == "true" ? "active" : "" %>">
        <%= check_box_tag "navigation_3d", "true", @navigation_3d == "true" %> 3D Navigation
      </label></div>
    <% end -%>
  </div>

  
</div>

app/views/visualize/index.js.erb
jQuery(document).ready(function() {
  
  var container;
  var camera, scene, renderer;
  var cube, plane;
  var targetRotation = 0;
  var targetRotationX = 0;
  var targetRotationOnMouseDown = 0;
  var targetRotationXOnMouseDown = 0;
  var mouseX = 0;
  var mouseY = 0;
  var mouseXOnMouseDown = 0;
  var mouseYOnMouseDown = 0;
  var innerWidth = <%= @inner_width %>;
  var innerHeight = <%= @inner_height %>;
  var windowHalfX = innerWidth / 2;
  var windowHalfY = innerHeight / 2;
  var cube_size = <%= @cube_size %>;
  var cube_padding = <%= @cube_padding %>;

  init();
  animate();

  function init() {
    container = document.getElementById("container");
    scene = new THREE.Scene();

    camera = new THREE.PerspectiveCamera( 70, innerWidth / innerHeight, 1, 100000 );
    camera.position.x = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )/2) %>;
    camera.position.y = <%= (@lines.count * ( @cube_size + @cube_padding )/4) %>;
    camera.position.z = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )/2)%>;
    scene.add( camera );

    // Cubes
    <% @lines.each_with_index do |line, index_line| %>
      position_y = 200 - (<%= index_line %> * (cube_size + cube_padding)) ;
      <% line.each_with_index do |cube, index_cube| %>
        position_x = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )/2) * -1%> + (<%= index_cube %> * (cube_size + cube_padding));
        <% if @show_grid == "true" %>  
        var plane = new THREE.Mesh(new THREE.PlaneGeometry(1,<%= (@max_cubes_per_line * ( @cube_size + @cube_padding )) / 2 %>), new THREE.MeshBasicMaterial({color: 0x000fff }));
        plane.doubleSided = true;
        plane.overdraw = true;
        plane.position.z = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )) / 4 * -1%>;
        plane.position.y = position_y;
        plane.position.x = position_x;
        scene.add(plane);
        <% end %>
        materials = [];
        for ( var i = 0; i < 6; i ++ ) {
          cube_color = new THREE.Color();
          cube_color.setRGB(
              <%= Setting.for_key("color_of-#{cube[:char]}-(r,g,b)").split(",")[0].to_f / 255 %>,
              <%= Setting.for_key("color_of-#{cube[:char]}-(r,g,b)").split(",")[1].to_f / 255 %>,
              <%= Setting.for_key("color_of-#{cube[:char]}-(r,g,b)").split(",")[2].to_f / 255 %>
          );
          materials.push( new THREE.MeshBasicMaterial( { color: cube_color.getHex()} ) );
        }
        
        <% if @calculation == "charcount" %>
          position_z = -<%= (cube[:count] * ( @cube_size + @cube_padding )) %> ;
        <% else %>
          position_z = 0;
        <% end %>
        cube_<%= index_cube %> = 
          new THREE.Mesh( 
              new THREE.CubeGeometry( 
                cube_size, cube_size, cube_size, 1, 1, 1, materials 
              ),
              new THREE.MeshFaceMaterial() 
          );
        cube_<%= index_cube %>.position.y = position_y;
        cube_<%= index_cube %>.position.x = position_x;
        cube_<%= index_cube %>.position.z = position_z;
        <% unless cube[:char] == " " %>
          scene.add( cube_<%= index_cube %> );
        <% end %>
      <% end %>
    <% end %>


    <% if Setting.for_key("Rendering_Engine_canvas_or_webGL", "canvas") == "canvas" %>
      renderer = new THREE.CanvasRenderer();
    <% else %>
      renderer = new THREE.WebGLRenderer();
    <% end %>
    renderer.setSize( innerWidth , innerHeight );

    container.appendChild( renderer.domElement );

    document.addEventListener( 'mousedown', onDocumentMouseDown, false );
    document.addEventListener( 'touchstart', onDocumentTouchStart, false );
    document.addEventListener( 'touchmove', onDocumentTouchMove, false );

    $("#button_3d").bind("click", function(){ 
        targetRotation = 0;
        camera.position.x = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )/2) %>;
        camera.position.y = <%= (@lines.count * ( @cube_size + @cube_padding )/4) %>;
        camera.position.z = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )/2)%>;
    });

    $("#button_2d").bind("click", function(){ 
        targetRotation = 0;
        camera.position.x = 0;
        camera.position.y = 0;
        camera.position.z = <%= (@max_cubes_per_line * ( @cube_size + @cube_padding )/2)%>;
        camera.lookAt(scene.position);
    });

    $("#button_left").bind("click", function(){ 
      targetRotation = 0;
      camera.position.x = x * Math.cos(0.1) + z * Math.sin(0.1);
      camera.position.z = z * Math.cos(0.1) - x * Math.sin(0.1);
      camera.lookAt(scene.position);
    });

    $("#button_right").bind("click", function(){ 
      targetRotation = 0;
      camera.position.x = x * Math.cos(0.1) - z * Math.sin(0.1);
      camera.position.z = z * Math.cos(0.1) + x * Math.sin(0.1);
      camera.lookAt(scene.position);
    });


    $("#button_up").bind("click", function(){ 
      camera.position.x -= 10;
      camera.position.z -= 10;
    }); 


    $("#button_down").bind("click", function(){ 
      camera.position.x += 10;
      camera.position.z += 10;
    });

  }

  //

  function onDocumentMouseDown( event ) {

    //event.preventDefault();
    targetRotation = 0;
    document.addEventListener( 'mousemove', onDocumentMouseMove, false );
    document.addEventListener( 'mouseup', onDocumentMouseUp, false );
    document.addEventListener( 'mouseout', onDocumentMouseOut, false );

    mouseXOnMouseDown = event.clientX - windowHalfX;
    mouseYOnMouseDown = event.clientY - windowHalfY;
    targetRotationOnMouseDown = targetRotation;
    targetRotationXOnMouseDown = targetRotationX;
  }

  function onDocumentMouseMove( event ) {

    mouseX = event.clientX - windowHalfX;
    mouseY = event.clientY - windowHalfY;

    targetRotation = targetRotationOnMouseDown + ( mouseX - mouseXOnMouseDown ) * 0.002;
    targetRotationX = targetRotationXOnMouseDown + ( mouseY - mouseYOnMouseDown ) * 0.002;
  }

  function onDocumentMouseUp( event ) {

    document.removeEventListener( 'mousemove', onDocumentMouseMove, false );
    document.removeEventListener( 'mouseup', onDocumentMouseUp, false );
    document.removeEventListener( 'mouseout', onDocumentMouseOut, false );
  }

  function onDocumentMouseOut( event ) {

    document.removeEventListener( 'mousemove', onDocumentMouseMove, false );
    document.removeEventListener( 'mouseup', onDocumentMouseUp, false );
    document.removeEventListener( 'mouseout', onDocumentMouseOut, false );
  }

  function onDocumentTouchStart( event ) {

    if ( event.touches.length == 1 ) {

      event.preventDefault();

      mouseXOnMouseDown = event.touches[ 0 ].pageX - windowHalfX;
      mouseYOnMouseDown = event.touches[ 0 ].pageY - windowHalfY;
      targetRotationOnMouseDown = targetRotation;

      targetRotationXOnMouseDown = targetRotationX;

    }
  }

  function onDocumentTouchMove( event ) {

    if ( event.touches.length == 1 ) {

      event.preventDefault();

      mouseX = event.touches[ 0 ].pageX - windowHalfX;
      mouseY = event.touches[ 0 ].pageY - windowHalfY;
      targetRotation = targetRotationOnMouseDown + ( mouseX - mouseXOnMouseDown ) * 0.05;
      targetRotationX = targetRotationXOnMouseDown + ( mouseY - mouseYOnMouseDown ) * 0.05;

    }
  }

  //

  function animate() {

    requestAnimationFrame( animate );
    render();

  }

  
  function render() {

    x = camera.position.x;
    z = camera.position.z;
    <% if @navigation_3d == "true"  %>
      camera.position.y = x * Math.cos(targetRotationX/10) + z * Math.sin(targetRotationX/10);
    <% end %>
    camera.position.x = x * Math.cos(targetRotation/10) + z * Math.sin(targetRotation/10);
    camera.position.z = z * Math.cos(targetRotation/10) - x * Math.sin(targetRotation/10);
    camera.lookAt(scene.position);


    
    //camera.position.y = ( targetRotation - camera.rotation.y ) * 0.05; 

    renderer.render( scene, camera );

  }
});